"""Write a level's gameplay data (game/data/levels/<id>.json) from its entity layout.

Usage: python3 tools/levels/export_level_data.py [level_id ...]   (default: every layout with entities)

The entity layout (tools/levels/layouts/<id>_entities.py) is the single source for where things are
and what they are (CLAUDE.md 7.1). The Blender build places them; this writes what they are, keyed
by stable id "<level>:<id>", for Undercity.Core (core/Undercity.Core/World/Tables.cs, LevelDef).
The output is generated: regenerate it, don't hand-edit it (CLAUDE.md 11).
"""

import importlib
import json
import pathlib
import sys

from shapely.geometry import Point, Polygon

ROOT = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tools" / "levels"))

KINDS = {"loot": "containers", "terminal": "terminals", "door": "doors", "trigger": "triggers",
         "exit": "exits", "zone": "zones", "item": "items"}
NO_DATA = {"spawn", "npc", "civ", "bed", "stash"}


def crowd_place(e, layout):
    """Where a civilian stands, for the crowd rule (openspec/changes/crowd-variety): the place in
    layout metres, the district it stands in (none between districts) and whether it is inside a
    named building (umbrellas are for outdoors)."""
    x, y = (float(v) for v in e["at"])
    pt = Point(x, y)
    district = next((d["name"].lower().replace(" ", "_") for d in layout.get("districts", [])
                     if Polygon(d["poly"]).covers(pt)), None)
    indoors = any(Polygon(b["poly"]).covers(pt) for b in layout.get("buildings", []))
    return {"at": [x, y], "district": district, "indoors": indoors}


def export(level_id):
    ents = importlib.import_module(f"layouts.{level_id}_entities").ENTITIES
    layout = importlib.import_module(f"layouts.{level_id}").MAP
    title = layout["title"].title()
    out = {"id": level_id, "title": title, "spawns": [],
           **{v: {} for v in KINDS.values()}, "npcs": {}, "crowd": {}, "water": [], "districts": []}
    # The layout's districts, for the conversation rig's gels (openspec/changes/character-lighting).
    for d in layout.get("districts", []):
        out["districts"].append({"id": d["name"].lower().replace(" ", "_"),
                                 "poly": [[float(x), float(y)] for x, y in d["poly"]]})
    # The layout's water bodies, for the core's water rule (openspec/changes/water-and-swimming).
    for w in layout.get("water", []):
        if "id" not in w:
            raise SystemExit(f"{level_id}: a water body has no id")
        out["water"].append({"id": w["id"], "surface_m": w["surface_m"], "bed_m": w["bed_m"],
                             "poly": [[float(x), float(y)] for x, y in w["poly"]]})
    # Stable ids share one namespace across kinds; spawns, beds and stashes are placements only.
    seen = set()
    for e in ents:
        kind, local = e["kind"], e["id"]
        key = (kind, local) if kind in NO_DATA - {"npc", "civ"} else local
        if key in seen:
            raise SystemExit(f"{level_id}: id '{local}' ({kind}) is used twice")
        seen.add(key)
        sid = f"{level_id}:{local}"
        if kind == "spawn":
            out["spawns"].append(local)
        elif kind == "npc":
            out["npcs"][sid] = e["props"]["npc"]
        elif kind == "civ":
            out["npcs"][sid] = "civ"
            out["crowd"][sid] = crowd_place(e, layout)
        elif kind in KINDS:
            if "data" not in e:
                raise SystemExit(f"{level_id}: {kind} '{local}' has no data")
            out[KINDS[kind]][sid] = e["data"]
        elif kind not in NO_DATA:
            raise SystemExit(f"{level_id}: unknown entity kind '{kind}'")
    path = ROOT / "game" / "data" / "levels" / f"{level_id}.json"
    header = f"// Generated by tools/levels/export_level_data.py from tools/levels/layouts/{level_id}_entities.py. Don't edit.\n"
    path.write_text(header + json.dumps(out, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"wrote {path.relative_to(ROOT)}: {sum(len(v) for v in out.values() if isinstance(v, dict))} records")


if __name__ == "__main__":
    ids = sys.argv[1:] or sorted(p.stem[:-len("_entities")] for p in (ROOT / "tools/levels/layouts").glob("*_entities.py"))
    for i in ids:
        export(i)
